name: Backend - Deploy to AWS Lambda
on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - ".github/workflows/backend.yml"

defaults:
  run:
    working-directory: backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: npm ci
        run: npm ci

      - name: Create env file
        run: |
          touch .env
          echo VITE_API_SERVER="${{ secrets.VITE_API_SERVER }}" >> .env
          cat .env

      - name: Run build
        run: npm run build

      - name: Deploy Lambda Function
        uses: aws-actions/aws-lambda-deploy@v1.1.0
        with:
          function-name: my-function-name
          code-artifacts-dir: dist
          handler: index.handler
          runtime: nodejs22.x
