name: Deploy to AWS S3
on:
  push:
    branches:
      - main
    paths:
      - frontend/**

defaults:
  run:
    working-directory: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm

      - name: npm ci
        run: npm ci

      - name: Create env file
        run: |
          touch .env
          echo VITE_API_SERVER="${{ secrets.VITE_API_SERVER }}" >> .env
          cat .env

      - name: Run build
        run: npm run build

      - name: Deploy S3 bucket
        run: aws s3 sync ./dist s3://inventory-frontend --delete
